"""
scripts/train_detector.py
=========================
Trains a YOLOv8 / YOLOv11 object detector on the prepared conveyor belt dataset.

Usage:
    python scripts/train_detector.py [--config config.yaml]
                                     [--model yolov8s.pt]
                                     [--data data/data.yaml]
                                     [--epochs 150]
                                     [--device cuda:0]

Prerequisites:
    - Labelled YOLO-format dataset at data/{train,val,test}/{images,labels}/
    - data/data.yaml (auto-generated by scripts/prepare_dataset.py)
    - GPU recommended (CUDA or MPS)
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

import yaml

ROOT = Path(__file__).parent.parent
sys.path.insert(0, str(ROOT))


def main():
    parser = argparse.ArgumentParser(description="Train YOLO detector on conveyor belt dataset")
    parser.add_argument("--config",  default="config.yaml", help="Path to config.yaml")
    parser.add_argument("--model",   default=None, help="Override: YOLO weights (e.g. yolov8s.pt)")
    parser.add_argument("--data",    default=None, help="Override: data.yaml path")
    parser.add_argument("--epochs",  type=int, default=None)
    parser.add_argument("--device",  default=None, help="torch device (cuda:0, cpu, mps)")
    parser.add_argument("--batch",   type=int, default=None)
    args = parser.parse_args()

    # Load config
    config_path = ROOT / args.config
    if not config_path.exists():
        print(f"[ERROR] Config not found: {config_path}")
        sys.exit(1)

    with open(config_path) as f:
        cfg = yaml.safe_load(f)

    train_cfg = cfg.get("train", {})

    # CLI overrides
    model   = args.model   or train_cfg.get("model",    "yolov8s.pt")
    data    = args.data    or str(ROOT / train_cfg.get("data_yaml", "data/data.yaml"))
    epochs  = args.epochs  or train_cfg.get("epochs",   150)
    device  = args.device  or train_cfg.get("device",   "")
    batch   = args.batch   or train_cfg.get("batch",    16)
    imgsz   = train_cfg.get("imgsz",          640)
    project = train_cfg.get("project",         "runs/detect")
    name    = train_cfg.get("name",            "conveyor_belt")

    if not Path(data).exists():
        print(
            f"[ERROR] data.yaml not found at '{data}'.\n"
            "  Run: python scripts/prepare_dataset.py  first."
        )
        sys.exit(1)

    print(f"[TrainDetector] Starting training:")
    print(f"  Model  : {model}")
    print(f"  Data   : {data}")
    print(f"  Epochs : {epochs}")
    print(f"  Device : {device or 'auto'}")
    print(f"  Batch  : {batch}")
    print(f"  ImgSz  : {imgsz}")
    print()

    try:
        from ultralytics import YOLO
    except ImportError:
        print("[ERROR] ultralytics not installed. Run: pip install ultralytics")
        sys.exit(1)

    model_obj = YOLO(model)

    results = model_obj.train(
        data=data,
        epochs=epochs,
        imgsz=imgsz,
        batch=batch,
        device=device if device else None,
        optimizer=train_cfg.get("optimizer",      "AdamW"),
        lr0=train_cfg.get("lr0",                  0.01),
        lrf=train_cfg.get("lrf",                  0.01),
        momentum=train_cfg.get("momentum",         0.937),
        weight_decay=train_cfg.get("weight_decay", 0.0005),
        warmup_epochs=train_cfg.get("warmup_epochs", 3.0),
        close_mosaic=train_cfg.get("close_mosaic", 10),
        project=project,
        name=name,
        exist_ok=True,
        verbose=True,
    )

    print(f"\n[TrainDetector] Training complete!")
    print(f"  Best weights : {results.save_dir}/weights/best.pt")
    print(f"  Last weights : {results.save_dir}/weights/last.pt")
    print(f"\n  Update config.yaml → detection.model_path to use the trained weights.")


if __name__ == "__main__":
    main()
